services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5

  airflow-init:
    build: .
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    command: db init
    depends_on:
      postgres:
        condition: service_healthy

  airflow-webserver:
    build: .
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__WEBSERVER__SECRET_KEY: "nyctaxi2024secretkey"
      DB_CONN: postgresql://airflow:airflow@postgres/airflow
      DBT_PROFILES_DIR: /opt/airflow/dbt_project
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL}
    ports:
      - "8081:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./ingestion:/opt/airflow/ingestion
      - ./dbt_project:/opt/airflow/dbt_project
      - ./logs:/opt/airflow/logs
    command: webserver
    depends_on:
      postgres:
        condition: service_healthy

  airflow-scheduler:
    build: .
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__WEBSERVER__SECRET_KEY: "nyctaxi2024secretkey"
      DB_CONN: postgresql://airflow:airflow@postgres/airflow
      DBT_PROFILES_DIR: /opt/airflow/dbt_project
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./ingestion:/opt/airflow/ingestion
      - ./dbt_project:/opt/airflow/dbt_project
      - ./logs:/opt/airflow/logs
    command: scheduler
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
